import "./globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "CompHub",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/code-icon-brackets.png" />
      </head>
      <body>
        {children} <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
